### ISSUE TITLE
`EventStream![Event + '_]`, which is in the documentation, does not compile

### ISSUE THREAD

**Issue by DanteFalzone0** [SergioBenitez/Rocket#2158]
**Description**

I am trying to use a borrowed value in an `EventStream`. [The documentation says here](https://api.rocket.rs/master/rocket/response/stream/struct.EventStream.html#borrowing) that the correct return type for a function that does this is `EventStream![Event + '_]`. However, the code does not compile, *even when copied almost verbatim from the documentation*.

**To Reproduce**

minimum main.rs that yields this problem (copied almost verbatim from the documentation):
```rust
#[macro_use] extern crate rocket;
use rocket::State;
use rocket::response::stream::{Event, EventStream};

#[get("/events")]
fn events(ctxt: &State<bool>) -> EventStream![Event + '_] {
    EventStream! {
        if *ctxt.inner() {
            yield Event::data("hi");
        }
    }
}

#[launch]
fn rocket() -> _ {
  rocket::build()
    .manage(true)
    .mount("/", routes![events])
}
```

**Expected Behavior**

Should compile and launch a webserver with an endpoint mounted at `/events` which can be used with an EventSource in Javascript to get an SSE event which says "hi".

**Actual Behavior**

Gives the following compiler error:
```
error[E0404]: expected trait, found struct `Event`
 --> src/main.rs:6:47
  |
6 | fn events(ctxt: &State<bool>) -> EventStream![Event + '_] {
  |                                               ^^^^^ not a trait
  |
help: `+` is used to constrain a "trait object" type with lifetimes or auto-traits; structs and enums can't be bound in that way
 --> src/main.rs:6:55
  |
6 | fn events(ctxt: &State<bool>) -> EventStream![Event + '_] {
  |                                               -----   ^^ ...because of this bound
  |                                               |
  |                                               expected this type to be a trait...
help: if you meant to use a type and not a trait here, remove the bounds
  |
6 - fn events(ctxt: &State<bool>) -> EventStream![Event + '_] {
6 + fn events(ctxt: &State<bool>) -> EventStream![Event] {
  | 

error[E0782]: trait objects must include the `dyn` keyword
 --> src/main.rs:6:47
  |
6 | fn events(ctxt: &State<bool>) -> EventStream![Event + '_] {
  |                                               ^^^^^^^^^^
  |
help: add `dyn` keyword before this trait
  |
6 | fn events(ctxt: &State<bool>) -> EventStream![dyn Event + '_] {
  |                                               +++

Some errors have detailed explanations: E0404, E0782.
For more information about an error, try `rustc --explain E0404`.
error: could not compile `test` due to 2 previous errors
exit status 101
```

**Environment:**

 - OS Distribution and Kernel: `uname -a` prints "Linux 62083f2def56 5.13.0-1024-gcp #​29~20.04.1-Ubuntu SMP Thu Apr 14 23:15:00 UTC 2022 x86_64 GNU/Linux"
 - Rocket Version: 0.5.0-rc.1

**Additional Context**

If I add the `dyn` keyword to the return type as the compiler suggests, it gives a different compiler error:
```
error[E0404]: expected trait, found struct `Event`
 --> src/main.rs:6:51
  |
6 | fn events(ctxt: &State<bool>) -> EventStream![dyn Event + '_] {
  |                                                   ^^^^^ not a trait
  |
help: `+` is used to constrain a "trait object" type with lifetimes or auto-traits; structs and enums can't be bound in that way
 --> src/main.rs:6:59
  |
6 | fn events(ctxt: &State<bool>) -> EventStream![dyn Event + '_] {
  |                                                   -----   ^^ ...because of this bound
  |                                                   |
  |                                                   expected this type to be a trait...
help: if you meant to use a type and not a trait here, remove the bounds
  |
6 - fn events(ctxt: &State<bool>) -> EventStream![dyn Event + '_] {
6 + fn events(ctxt: &State<bool>) -> EventStream![dyn Event] {
  | 

For more information about this error, try `rustc --explain E0404`.
error: could not compile `test` due to previous error
exit status 101
```

**Comment by SergioBenitez** [comment]
This doesn't exist in 0.5-rc, the version you're using, and only exists in `master`. You should either use master or reconfigure your code to allocate as necessary.

**Comment by lafleurdeboum** [comment]
I found this issue when migrating some code that relied on 0.5-rc . I just want to mention that using the `EventStream![Event + '_]` signature works in Rocket 0.5 - I can confirm the proposed main.rs builds and runs.
