### ISSUE TITLE
#[derive(FromForm)] not working on v0.4.5

### ISSUE THREAD

**Issue by FrontMage** [SergioBenitez/Rocket#1326]
## Bug Reports

Bug reports _must_ include:

  1. The version of Rocket you're using. Ensure it's the latest, if possible.
`0.4.5`
  2. The operating system (distribution and version) where the issue occurs.
`5.4.39-1-MANJARO`
  3. A brief description of the bug that includes:
I try to use `#[derive(FromForm)]` to my simple struct:
```rust
    #[derive(FromForm, Deserialize)]
    pub struct Request {
        pub a: i32,
        pub b: i32,
    }
```
Then use it in a get router:
```rust
#[get("/?<req>")]
fn get(req: fns::fns::Request) -> Json<fns::fns::Response> {
    Json(fns::fns::func(req))
}
```
But it complaints about `Request` did not implement `FromFormValue`:
```bash
cargo check                                                                                                          
Checking rust v0.1.0 (/home/xinbg/Documents/fx/assets/dockerfiles/base/rust)
error[E0277]: the trait bound `fns::fns::Request: rocket::request::FromFormValue<'_>` is not satisfied
  --> src/main.rs:15:8
   |
15 | fn get(req: fns::fns::Request) -> Json<fns::fns::Response> {
   |        ^^^^^^^^^^^^^^^^^^^^^^ the trait `rocket::request::FromFormValue<'_>` is not implemented for `fns::fns::Request`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `rust`.

To learn more, run the command again with --verbose.
```
  4. How you uncovered the bug. Short, reproducible tests are especially useful.
You can find my code on [https://github.com/FrontMage/fx/blob/support-Rust/assets/dockerfiles/base/rust/src/main.rs](url), just clone it and run `cargo check`.
  5. Ideas, if any, about what Rocket is doing incorrectly.
From this documentation [https://api.rocket.rs/v0.4/rocket/request/trait.FromFormValue.html](url), it says `Rocket implements FromFormValue for many standard library types. ` which includes `i32`.
I suppose my struct will work out of the box.

**Comment by SergioBenitez** [comment]
Your type in the handler should be `Form<Request>` or `LenientForm<Request>`. See the [`FromForm`](https://api.rocket.rs/v0.4/rocket/request/trait.FromForm.html) docs and the [Forms guide](https://rocket.rs/v0.4/guide/requests/#forms) for examples.

**Comment by FrontMage** [comment]
@SergioBenitez I kind of tried this method, originally it was 
```rust
#[get("/?<req>")]
fn get(req: Form<fns::fns::Request>) -> Json<fns::fns::Response> {
    Json(fns::fns::func(req.0))
}
```
But it still posts these errors
```bash
Checking rust v0.1.0 (/home/xinbg/Documents/fx/assets/dockerfiles/base/rust)
error[E0277]: the trait bound `rocket::request::Form<fns::fns::Request>: rocket::request::FromFormValue<'_>` is not satisfied
  --> src/main.rs:16:8
   |
16 | fn get(req: Form<fns::fns::Request>) -> Json<fns::fns::Response> {
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `rocket::request::FromFormValue<'_>` is not implemented for `rocket::request::Form<fns::fns::Request>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `rust`.

To learn more, run the command again with --verbose.
```

**Comment by SergioBenitez** [comment]
Please read the docs carefully. You need:

```rust
#[get("/?<req..>")]
fn get(req: Form<fns::fns::Request>) -> Json<fns::fns::Response> { ... }
```

Note the `..` in the parameter name.

**Comment by FrontMage** [comment]
Sorry my bad
