### ISSUE TITLE
Compile error when LenientForm used at querystring

### ISSUE THREAD

**Issue by fluxxu** [SergioBenitez/Rocket#570]
## Bug Reports

  1. The version of Rocket you're using. Ensure it's the latest, if possible.
=0.3.6

  2. The operating system (distribution and version) where the issue occurs.
MacOS 10.13.3
rustc 1.25.0-nightly (56733bc9f 2018-02-01)
rustc 1.25.0-nightly (b1f8e6fb0 2018-02-22)
  3. A brief description of the bug that includes:
LenientForm<T> can not be used for parsing querystring

  4. How you uncovered the bug. Short, reproducible tests are especially useful.
This code cannot compile
```rust
#[derive(FromForm)]
pub struct Query {
  sku: Option<String>,
}

#[get("/path?<query>")]
pub fn callback_fetch_stock(query: LenientForm<Query>) {}
```
got
```
error[E0277]: the trait bound `rocket::request::LenientForm<'_, routes::channels::shopify::Query>: rocket::request::FromForm<'_>` is not satisfied
  --> test.rs:54:1
   |
54 | #[get("/path?<query>")]
   | ^^^^^^^^^^^^^^^^^^^^^^^ the trait `rocket::request::FromForm<'_>` is not implemented for `rocket::request::LenientForm<'_, routes::channels::shopify::Query>`
   |
   = note: required by `rocket::request::FromForm::from_form`
```
but if I change the code to
```rust
#[derive(FromForm)]
pub struct Query {
  sku: Option<String>,
}

#[put("/path", data = "<query>")]
pub fn callback_fetch_stock(query: LenientForm<Query>) {}
```
It compiles successfully.
  5. Ideas, if any, about what Rocket is doing incorrectly.

**Comment by SergioBenitez** [comment]
This is not a bug. `LenientForm` does not implement `FromForm`, so it cannot be used in that position. You can either use `Query` directly with the derive or implement `FromForm` yourself.

I expect `LenientForm` to work in that position in 0.4, however, when query handling is changed significantly.
