### ISSUE TITLE
Regression when upgrading to 0.4.9

### ISSUE THREAD

**Issue by jeluard** [SergioBenitez/Rocket#1647]
## Bug Reports

I am facing a compilation issue when upgrading from `0.4.7` to `0.4.9`. The following code in a `FromRequest` implementation used to work:

```rust
fn from_request(request: &'a Request<'r>) -> request::Outcome<LoggedUser, String> {
            let runtime = Runtime::new().map_err(|_| {
                Err((
                    Status::ExpectationFailed,
                    "Failed to execute async fn".to_string(),
                ))
            })?;
...
}
```

It now fails to compile with the following message:

```rust
error[E0277]: `?` couldn't convert the error to `(rocket::http::Status, std::string::String)`
  --> src/api.rs:59:15
   |
59 |             })?;
   |               ^ the trait `std::convert::From<std::result::Result<_, (rocket::http::Status, std::string::String)>>` is not implemented for `(rocket::http::Status, std::string::String)`
   |
   = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
   = help: the following implementations were found:
             <(usize, usize) as std::convert::From<toml::tokens::Span>>
   = note: required because of the requirements on the impl of `FromResidual<std::result::Result<Infallible, std::result::Result<_, (rocket::http::Status, std::string::String)>>>` for `Outcome<LoggedUser, (rocket::http::Status, std::string::String), ()>`
   = note: required by `from_residual`
```

My rust foo being limited, I am not clear if this can be fixed in my code or if this is considered a regression.

**Comment by SergioBenitez** [comment]
If this worked before, then there indeed has been a breaking change. This is due to #1642. That is, this is an unfortunate necessary breaking change caused by a new Rust nightly.

I believe we had previously hacked around the inability to properly support `?` for `Outcome` by using `Into` for `Result`, but since 0.4.9, we can directly support internal error types. Suffice to say that you need simple change your implementation to what it _should_ have been all along (no `Err` internally):

```rust
let runtime = Runtime::new()
  .map_err(|_| (Status::ExpectationFailed, "Failed to execute async fn".to_string()))?;
```

**Comment by SergioBenitez** [comment]
Please reopen this issue if my comment above does not resolve the breakage.
