### ISSUE TITLE
Rocket 0.4.7 fails to build on rustc 1.54.0-nightly (4e3e6db01 2021-05-18)

### ISSUE THREAD

**Issue by lambda-fairy** [SergioBenitez/Rocket#1642]
See https://github.com/lambda-fairy/maud/runs/2616219008?check_suite_focus=true

```
error[E0437]: type `Ok` is not a member of trait `Try`
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.7/src/outcome.rs:607:5
    |
607 |     type Ok = S;
    |     ^^^^^^^^^^^^ not a member of trait `Try`

error[E0437]: type `Error` is not a member of trait `Try`
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.7/src/outcome.rs:608:5
    |
608 |     type Error = Result<F, E>;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^ not a member of trait `Try`

error[E0407]: method `into_result` is not a member of trait `Try`
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.7/src/outcome.rs:610:5
    |
610 | /     fn into_result(self) -> Result<Self::Ok, Self::Error> {
611 | |         match self {
612 | |             Success(val) => Ok(val),
613 | |             Forward(val) => Err(Ok(val)),
614 | |             Failure(val) => Err(Err(val)),
615 | |         }
616 | |     }
    | |_____^ not a member of trait `Try`

error[E0407]: method `from_error` is not a member of trait `Try`
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.7/src/outcome.rs:618:5
    |
618 | /     fn from_error(val: Self::Error) -> Self {
619 | |         match val {
620 | |             Ok(val) => Forward(val),
621 | |             Err(val) => Failure(val),
622 | |         }
623 | |     }
    | |_____^ not a member of trait `Try`

error[E0407]: method `from_ok` is not a member of trait `Try`
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.7/src/outcome.rs:625:5
    |
625 | /     fn from_ok(val: Self::Ok) -> Self {
626 | |         Success(val)
627 | |     }
    | |_____^ not a member of trait `Try`

error[E0658]: use of unstable library feature 'try_trait_v2'
  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.7/src/outcome.rs:84:5
   |
84 | use std::ops::Try;
   |     ^^^^^^^^^^^^^
   |
   = note: see issue #84277 <https://github.com/rust-lang/rust/issues/84277> for more information
   = help: add `#![feature(try_trait_v2)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'try_trait_v2'
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.7/src/outcome.rs:606:15
    |
606 | impl<S, E, F> Try for Outcome<S, E, F> {
    |               ^^^
    |
    = note: see issue #84277 <https://github.com/rust-lang/rust/issues/84277> for more information
    = help: add `#![feature(try_trait_v2)]` to the crate attributes to enable

error[E0220]: associated type `Ok` not found for `Self`
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.7/src/outcome.rs:610:42
    |
610 |     fn into_result(self) -> Result<Self::Ok, Self::Error> {
    |                                          ^^ associated type `Ok` not found

error[E0220]: associated type `Error` not found for `Self`
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.7/src/outcome.rs:610:52
    |
610 |     fn into_result(self) -> Result<Self::Ok, Self::Error> {
    |                                                    ^^^^^ associated type `Error` not found

error[E0220]: associated type `Error` not found for `Self`
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.7/src/outcome.rs:618:30
    |
618 |     fn from_error(val: Self::Error) -> Self {
    |                              ^^^^^ associated type `Error` not found

error[E0220]: associated type `Ok` not found for `Self`
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.7/src/outcome.rs:625:27
    |
625 |     fn from_ok(val: Self::Ok) -> Self {
    |                           ^^ associated type `Ok` not found

error: aborting due to 11 previous errors
```

**Comment by SergioBenitez** [comment]
Looks like tryv2 has landed! Exciting times. Pushing a fix soon.

**Comment by SergioBenitez** [comment]
Fixed in https://github.com/SergioBenitez/Rocket/commit/425f741b873424046e20855f3fe13a3eb01b0c5e. Releasing soon.

**Comment by SergioBenitez** [comment]
`v0.4.8` is out.

**Comment by lambda-fairy** [comment]
Thanks for the quick turnaround Sergio!
