### ISSUE TITLE
Rocket failing to compile when following the quick start guide. 

### ISSUE THREAD

**Issue by nerandell** [SergioBenitez/Rocket#1950]
**Description**

Rocket is failing to compile after following the instructions in the quick start guide. 

Cargo run output:

```
Compiling rocket v0.4.10
error[E0277]: the trait bound `(dyn handler::Handler + 'static): handler::Handler` is not satisfied
   --> /Users/achandaw/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.10/src/rocket.rs:299:41
    |
299 |             let outcome = route.handler.handle(request, data);
    |                                         ^^^^^^ the trait `handler::Handler` is not implemented for `(dyn handler::Handler + 'static)`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `rocket` due to previous error
```

**To Reproduce**

main.rs:

```rust
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use] extern crate rocket;

#[get("/")]
fn index() -> &'static str {
    "Hello, world!"
}

fn main() {
    rocket::ignite().mount("/", routes![index]).launch();
}
```

Cargo.toml:
```
[package]
name = "rocket_hello_world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.10"
```

**Expected Behavior**

Rocket should successfully compile.

**Environment:**

 - OS - macOS 11.6
 - Rocket version - 0.4.10

**Comment by nerandell** [comment]
Works correctly with `0.5.0-rc.1`. Please ignore the issue.
